// Code generated by the Lingua Franca compiler from:
// file://home/zero/lf-workspace/ExampleHello/src/HelloWorld.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/home/zero/lf-workspace/ExampleHello/src-gen/HelloWorld"
#include "include/ctarget/ctarget.h"
#include "core/threaded/reactor_threaded.c"
#include "core/threaded/scheduler.h"
#include "core/mixed_radix.h"
int main(int argc, char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
// =============== START reactor class HelloWorld
typedef struct {
    struct self_base_t base;
    reaction_t _lf__reaction_0;
    trigger_t _lf__t;
    reaction_t* _lf__t_reactions[1];
} helloworld_self_t;
#include "include/ctarget/set.h"
void helloworldreaction_function_0(void* instance_args) {
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wunused-variable"
    helloworld_self_t* self = (helloworld_self_t*)instance_args;
    #pragma GCC diagnostic pop
    // Using a thread-safe print function provided by the runtime.
    info_print("Hello World!");
        
}
#include "include/ctarget/set_undef.h"
helloworld_self_t* new_HelloWorld() {
    helloworld_self_t* self = (helloworld_self_t*)_lf_new_reactor(sizeof(helloworld_self_t));
    self->_lf__reaction_0.number = 0;
    self->_lf__reaction_0.function = helloworldreaction_function_0;
    self->_lf__reaction_0.self = self;
    self->_lf__reaction_0.deadline_violation_handler = NULL;
    self->_lf__reaction_0.STP_handler = NULL;
    self->_lf__reaction_0.name = "?";
    self->_lf__reaction_0.mode = NULL;
    self->_lf__t.last = NULL;
    self->_lf__t_reactions[0] = &self->_lf__reaction_0;
    self->_lf__t.reactions = &self->_lf__t_reactions[0];
    self->_lf__t.number_of_reactions = 1;
    self->_lf__t.is_timer = true;
    return self;
}
// =============== END reactor class HelloWorld
// Array of pointers to timer triggers to be scheduled in _lf_initialize_timers().
trigger_t* _lf_timer_triggers[1];
int _lf_timer_triggers_size = 1;
// Array of pointers to shutdown triggers.
reaction_t** _lf_shutdown_reactions = NULL;
int _lf_shutdown_reactions_size = 0;
trigger_t* _lf_action_for_port(int port_id) {
        return NULL;
}
void _lf_initialize_trigger_objects() {
    // Initialize the _lf_clock
    lf_initialize_clock();
    _lf_startup_reactions = (reaction_t**)calloc(0, sizeof(reaction_t*));
    _lf_startup_reactions_size = 0;
    int _lf_startup_reactions_count = 0;
    int _lf_shutdown_reactions_count = 0;
    int _lf_timer_triggers_count = 0;
    int _lf_tokens_with_ref_count_count = 0;
    helloworld_self_t* helloworld_self[1];
    // ***** Start initializing HelloWorld of class HelloWorld
    helloworld_self[0] = new_HelloWorld();
    int bank_index = 0;
    // Initializing timer HelloWorld.t.
    helloworld_self[0]->_lf__t.offset = 0;
    helloworld_self[0]->_lf__t.period = SEC(1);
    _lf_timer_triggers[_lf_timer_triggers_count++] = &helloworld_self[0]->_lf__t;
    helloworld_self[0]->_lf__t.mode = NULL;
    //***** End initializing HelloWorld
    // **** Start deferred initialize for HelloWorld
    {
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_0 of HelloWorld.
        helloworld_self[0]->_lf__reaction_0.num_outputs = 0;
        {
            int count = 0;
        }
        
        // ** End initialization for reaction 0 of HelloWorld
    }
    // **** End of deferred initialize for HelloWorld
    // **** Start non-nested deferred initialize for HelloWorld
    // **** End of non-nested deferred initialize for HelloWorld
    // Connect inputs and outputs for reactor HelloWorld.
    // Set reaction priorities for ReactorInstance HelloWorld
    {
        helloworld_self[0]->_lf__reaction_0.chain_id = 1;
        // index is the OR of level 0 and 
        // deadline 140737488355327 shifted left 16 bits.
        helloworld_self[0]->_lf__reaction_0.index = 0x7fffffffffff0000LL;
    }
    // Initialize the scheduler
    size_t num_reactions_per_level[1] = 
        {1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 1};
    lf_sched_init(
        (size_t)_lf_number_of_workers,
        &sched_params
    );
}
void _lf_trigger_startup_reactions() {
}
void _lf_initialize_timers() {
    for (int i = 0; i < _lf_timer_triggers_size; i++) {
        if (_lf_timer_triggers[i] != NULL) {
            _lf_initialize_timer(_lf_timer_triggers[i]);
        }
    }
}
void logical_tag_complete(tag_t tag_to_send) {
}
bool _lf_trigger_shutdown_reactions() {
    // Return true if there are shutdown reactions.
    return (_lf_shutdown_reactions_size > 0);
}
void terminate_execution() {}
